import { describe, it, expect } from 'vitest'
import { exportManifest } from './exporter'

const MANIFEST = {
  frontmatter: { name: 'Test Agent', version: '1.0.0', description: 'A test agent' },
  sections: {
    Role: 'You are a test agent.',
    Capabilities: '- Do testing\n- Assert results',
    Constraints: '- No side effects',
    Memory: '',
    Tools: '- bash: read-only',
    Workflow: '1. Think\n2. Act',
  },
}

describe('exportManifest — claude', () => {
  it('contains role content', () => {
    expect(exportManifest(MANIFEST, 'claude')).toContain('You are a test agent.')
  })
  it('contains constraints', () => {
    expect(exportManifest(MANIFEST, 'claude')).toContain('No side effects')
  })
  it('contains tools', () => {
    expect(exportManifest(MANIFEST, 'claude')).toContain('bash: read-only')
  })
  it('includes generated-by comment', () => {
    expect(exportManifest(MANIFEST, 'claude')).toContain('Generated by agentos.md')
  })
  it('skips empty Memory section', () => {
    const output = exportManifest(MANIFEST, 'claude')
    const lines = output.split('\n')
    const memIdx = lines.findIndex(l => l.trim() === '## Memory Configuration')
    if (memIdx !== -1) {
      expect(lines[memIdx + 1].trim()).not.toBe('')
    }
  })
})

describe('exportManifest — openai', () => {
  it('contains role content', () => {
    expect(exportManifest(MANIFEST, 'openai')).toContain('You are a test agent.')
  })
  it('contains constraints', () => {
    expect(exportManifest(MANIFEST, 'openai')).toContain('No side effects')
  })
})

describe('exportManifest — gemini', () => {
  it('contains role content', () => {
    expect(exportManifest(MANIFEST, 'gemini')).toContain('You are a test agent.')
  })
})

describe('exportManifest — edge cases', () => {
  it('throws on unknown platform', () => {
    expect(() => exportManifest(MANIFEST, 'unknown')).toThrow('Unknown platform')
  })
})
