const HEADER = '<!-- Generated by agentos.md — Agent Manifest Standard v0.1 -->\n\n'

function section(title, content) {
  if (!content || !content.trim()) return ''
  return `## ${title}\n\n${content.trim()}\n\n`
}

function agentMeta(frontmatter) {
  return `<!-- Agent: ${frontmatter.name || 'Unnamed'} v${frontmatter.version || '0.0.0'} -->\n\n`
}

export function exportManifest(manifest, platform) {
  const { frontmatter, sections } = manifest
  const meta = agentMeta(frontmatter)

  if (platform === 'claude') {
    return (
      HEADER + meta +
      section('Role', sections.Role) +
      section('Capabilities', sections.Capabilities) +
      section('Constraints', sections.Constraints) +
      section('Memory Configuration', sections.Memory) +
      section('Allowed Tools', sections.Tools) +
      section('Workflow', sections.Workflow)
    ).trimEnd() + '\n'
  }

  if (platform === 'openai') {
    return (
      HEADER + meta +
      section('System Instructions', sections.Role) +
      section('Capabilities', sections.Capabilities) +
      section('Constraints', sections.Constraints) +
      section('Tools', sections.Tools) +
      section('Workflow', sections.Workflow)
    ).trimEnd() + '\n'
  }

  if (platform === 'gemini') {
    return (
      HEADER + meta +
      section('Role', sections.Role) +
      section('Capabilities', sections.Capabilities) +
      section('Constraints', sections.Constraints) +
      section('Tools', sections.Tools) +
      section('Workflow', sections.Workflow)
    ).trimEnd() + '\n'
  }

  if (platform === 'hermes') {
    return (
      HEADER + meta +
      section('Identity', sections.Role) +
      section('Capabilities', sections.Capabilities) +
      section('Behavioral Boundaries', sections.Constraints) +
      section('Tools', sections.Tools) +
      section('Operational Workflow', sections.Workflow)
    ).trimEnd() + '\n'
  }

  if (platform === 'cursor') {
    const { name, description } = frontmatter
    const fmDesc = [name, description].filter(Boolean).join(' — ')
    const fm = `---\ndescription: "${fmDesc.replace(/"/g, '\\"')}"\nglobs: **/*\n---\n\n`
    const roleText = sections.Role ? sections.Role.trim() + '\n\n' : ''
    return (
      fm + roleText +
      section('Capabilities', sections.Capabilities) +
      section('Constraints', sections.Constraints) +
      section('Tools', sections.Tools) +
      section('Workflow', sections.Workflow)
    ).trimEnd() + '\n'
  }

  if (platform === 'windsurf') {
    const roleText = sections.Role ? sections.Role.trim() + '\n\n' : ''
    return (
      HEADER + meta + roleText +
      section('Capabilities', sections.Capabilities) +
      section('Constraints', sections.Constraints) +
      section('Tools', sections.Tools) +
      section('Workflow', sections.Workflow)
    ).trimEnd() + '\n'
  }

  throw new Error(`Unknown platform: ${platform}`)
}
